spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  application:
    name: qima-test

server:
  port: 8080
